/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ConstructorLabRouteImport } from './routes/constructor-lab'
import { Route as ConstructorAiV31RouteImport } from './routes/constructor-ai-v3-1'
import { Route as ConstructorAiV3RouteImport } from './routes/constructor-ai-v3'
import { Route as ConstructorRouteImport } from './routes/constructor'
import { Route as ConcreteRouteImport } from './routes/concrete'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiLeadRouteImport } from './routes/api.lead'
import { Route as ApiAiLayoutRouteImport } from './routes/api.ai-layout'
import { Route as BlogTagTagRouteImport } from './routes/blog.tag.$tag'
import { Route as BlogCategoryCategoryRouteImport } from './routes/blog.category.$category'
import { Route as ApiAiLayoutFootprintRouteImport } from './routes/api.ai-layout.footprint'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructorLabRoute = ConstructorLabRouteImport.update({
  id: '/constructor-lab',
  path: '/constructor-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructorAiV31Route = ConstructorAiV31RouteImport.update({
  id: '/constructor-ai-v3-1',
  path: '/constructor-ai-v3-1',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructorAiV3Route = ConstructorAiV3RouteImport.update({
  id: '/constructor-ai-v3',
  path: '/constructor-ai-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructorRoute = ConstructorRouteImport.update({
  id: '/constructor',
  path: '/constructor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcreteRoute = ConcreteRouteImport.update({
  id: '/concrete',
  path: '/concrete',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiLayoutRoute = ApiAiLayoutRouteImport.update({
  id: '/api/ai-layout',
  path: '/api/ai-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagTagRoute = BlogTagTagRouteImport.update({
  id: '/blog/tag/$tag',
  path: '/blog/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryCategoryRoute = BlogCategoryCategoryRouteImport.update({
  id: '/blog/category/$category',
  path: '/blog/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiLayoutFootprintRoute = ApiAiLayoutFootprintRouteImport.update({
  id: '/footprint',
  path: '/footprint',
  getParentRoute: () => ApiAiLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concrete': typeof ConcreteRoute
  '/constructor': typeof ConstructorRoute
  '/constructor-ai-v3': typeof ConstructorAiV3Route
  '/constructor-ai-v3-1': typeof ConstructorAiV31Route
  '/constructor-lab': typeof ConstructorLabRoute
  '/contacts': typeof ContactsRoute
  '/portfolio': typeof PortfolioRoute
  '/presentation': typeof PresentationRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/api/ai-layout': typeof ApiAiLayoutRouteWithChildren
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/ai-layout/footprint': typeof ApiAiLayoutFootprintRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concrete': typeof ConcreteRoute
  '/constructor': typeof ConstructorRoute
  '/constructor-ai-v3': typeof ConstructorAiV3Route
  '/constructor-ai-v3-1': typeof ConstructorAiV31Route
  '/constructor-lab': typeof ConstructorLabRoute
  '/contacts': typeof ContactsRoute
  '/portfolio': typeof PortfolioRoute
  '/presentation': typeof PresentationRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/api/ai-layout': typeof ApiAiLayoutRouteWithChildren
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/ai-layout/footprint': typeof ApiAiLayoutFootprintRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concrete': typeof ConcreteRoute
  '/constructor': typeof ConstructorRoute
  '/constructor-ai-v3': typeof ConstructorAiV3Route
  '/constructor-ai-v3-1': typeof ConstructorAiV31Route
  '/constructor-lab': typeof ConstructorLabRoute
  '/contacts': typeof ContactsRoute
  '/portfolio': typeof PortfolioRoute
  '/presentation': typeof PresentationRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/api/ai-layout': typeof ApiAiLayoutRouteWithChildren
  '/api/lead': typeof ApiLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/ai-layout/footprint': typeof ApiAiLayoutFootprintRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concrete'
    | '/constructor'
    | '/constructor-ai-v3'
    | '/constructor-ai-v3-1'
    | '/constructor-lab'
    | '/contacts'
    | '/portfolio'
    | '/presentation'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/technology'
    | '/api/ai-layout'
    | '/api/lead'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog/'
    | '/api/ai-layout/footprint'
    | '/blog/category/$category'
    | '/blog/tag/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concrete'
    | '/constructor'
    | '/constructor-ai-v3'
    | '/constructor-ai-v3-1'
    | '/constructor-lab'
    | '/contacts'
    | '/portfolio'
    | '/presentation'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/technology'
    | '/api/ai-layout'
    | '/api/lead'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog'
    | '/api/ai-layout/footprint'
    | '/blog/category/$category'
    | '/blog/tag/$tag'
  id:
    | '__root__'
    | '/'
    | '/concrete'
    | '/constructor'
    | '/constructor-ai-v3'
    | '/constructor-ai-v3-1'
    | '/constructor-lab'
    | '/contacts'
    | '/portfolio'
    | '/presentation'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/technology'
    | '/api/ai-layout'
    | '/api/lead'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog/'
    | '/api/ai-layout/footprint'
    | '/blog/category/$category'
    | '/blog/tag/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConcreteRoute: typeof ConcreteRoute
  ConstructorRoute: typeof ConstructorRoute
  ConstructorAiV3Route: typeof ConstructorAiV3Route
  ConstructorAiV31Route: typeof ConstructorAiV31Route
  ConstructorLabRoute: typeof ConstructorLabRoute
  ContactsRoute: typeof ContactsRoute
  PortfolioRoute: typeof PortfolioRoute
  PresentationRoute: typeof PresentationRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TechnologyRoute: typeof TechnologyRoute
  ApiAiLayoutRoute: typeof ApiAiLayoutRouteWithChildren
  ApiLeadRoute: typeof ApiLeadRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategoryCategoryRoute: typeof BlogCategoryCategoryRoute
  BlogTagTagRoute: typeof BlogTagTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructor-lab': {
      id: '/constructor-lab'
      path: '/constructor-lab'
      fullPath: '/constructor-lab'
      preLoaderRoute: typeof ConstructorLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructor-ai-v3-1': {
      id: '/constructor-ai-v3-1'
      path: '/constructor-ai-v3-1'
      fullPath: '/constructor-ai-v3-1'
      preLoaderRoute: typeof ConstructorAiV31RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructor-ai-v3': {
      id: '/constructor-ai-v3'
      path: '/constructor-ai-v3'
      fullPath: '/constructor-ai-v3'
      preLoaderRoute: typeof ConstructorAiV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructor': {
      id: '/constructor'
      path: '/constructor'
      fullPath: '/constructor'
      preLoaderRoute: typeof ConstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concrete': {
      id: '/concrete'
      path: '/concrete'
      fullPath: '/concrete'
      preLoaderRoute: typeof ConcreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-layout': {
      id: '/api/ai-layout'
      path: '/api/ai-layout'
      fullPath: '/api/ai-layout'
      preLoaderRoute: typeof ApiAiLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$tag': {
      id: '/blog/tag/$tag'
      path: '/blog/tag/$tag'
      fullPath: '/blog/tag/$tag'
      preLoaderRoute: typeof BlogTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$category': {
      id: '/blog/category/$category'
      path: '/blog/category/$category'
      fullPath: '/blog/category/$category'
      preLoaderRoute: typeof BlogCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-layout/footprint': {
      id: '/api/ai-layout/footprint'
      path: '/footprint'
      fullPath: '/api/ai-layout/footprint'
      preLoaderRoute: typeof ApiAiLayoutFootprintRouteImport
      parentRoute: typeof ApiAiLayoutRoute
    }
  }
}

interface ApiAiLayoutRouteChildren {
  ApiAiLayoutFootprintRoute: typeof ApiAiLayoutFootprintRoute
}

const ApiAiLayoutRouteChildren: ApiAiLayoutRouteChildren = {
  ApiAiLayoutFootprintRoute: ApiAiLayoutFootprintRoute,
}

const ApiAiLayoutRouteWithChildren = ApiAiLayoutRoute._addFileChildren(
  ApiAiLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConcreteRoute: ConcreteRoute,
  ConstructorRoute: ConstructorRoute,
  ConstructorAiV3Route: ConstructorAiV3Route,
  ConstructorAiV31Route: ConstructorAiV31Route,
  ConstructorLabRoute: ConstructorLabRoute,
  ContactsRoute: ContactsRoute,
  PortfolioRoute: PortfolioRoute,
  PresentationRoute: PresentationRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TechnologyRoute: TechnologyRoute,
  ApiAiLayoutRoute: ApiAiLayoutRouteWithChildren,
  ApiLeadRoute: ApiLeadRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategoryCategoryRoute: BlogCategoryCategoryRoute,
  BlogTagTagRoute: BlogTagTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
